apiVersion: apps/v1
kind: Deployment
metadata:
  name: dh8rhd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dh8rhd
  template:
    metadata:
      labels:
        app: dh8rhd
    spec:
      containers:
      - image: okteto.dev/dh8rhd:latest
        name: dh8rhd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "e575f412-683c-463b-835a-05b6ee94e2e5"
        - name: Vless_Path
          value: "/vl11"
        - name: Vmess_UUID
          value: "e575f412-683c-463b-835a-05b6ee94e2e5"
        - name: Vmess_Path
          value: "/vm22"
        - name: Share_Path
          value: "/v2link"
