apiVersion: v1
kind: Service
metadata:
  name: dh8rhd
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "dh8rhd"
    port: 8080
  selector:
    app: dh8rhd
